spring:
  application:
    name: sportsfacility_backend

  datasource:
    url: jdbc:mysql://localhost:3306/sportsfacility_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
    open-in-view: false


  mail:
    host: smtp.gmail.com
    port: 587
    username: tpn18092004@gmail.com
    password: gtzgsmjcdzanimek
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
server:
  port: 8080

jwt:
  secret: oUwfZl+T7r7+Jw5bB65zW98Mt3jzYtPClpZ3aINxqVQ=
  expiration: 86400000 # 24 hours in milliseconds

cloudinary:
  cloud-name: dwd4b8lcx
  api-key: 271116451416351
  api-secret: fbyd8zzUl4OSzBFxkf4_cr4jNTk